<div id="facebookPostPreview" style="float: left; margin-top: 10px;">
    <div style="float: left; width: 60px;">
        <img class="pagePhotoURL" src="{{PAGE_PHOTO_URL}}" style="float: left; width: 50px;" />
    </div>
    <div style="float: left; width: 398px;">
        <a href="#" style="color: #3B5998; cursor: pointer; font: bold 11px 'lucida grande',tahoma,verdana,arial,sans-serif; text-decoration: none;">Creasoupers</a>
        <p class="postBrief" style="font: 11px 'lucida grande',tahoma,verdana,arial,sans-serif; margin-top: 3px;">{{POST_BRIEF}}</p>
        <div style="float: left; width: 100%;">
            <div style="float: left; width: 100px;">
                <img class="postPhotoURL" src="{{POST_PHOTO_URL}}" style="height: 90px; width: 90px;" />
            </div>
            <div style="float: left; width: 298px;">
                <a class="postURL" href="{{POST_URL}}" style="color: #3B5998; cursor: pointer; font: bold 11px 'lucida grande',tahoma,verdana,arial,sans-serif; text-decoration: none;">{{POST_TITLE}}</a>
                <p class="postURLDomain" style="color: gray; font: 11px 'lucida grande',tahoma,verdana,arial,sans-serif; margin-bottom: 0; margin-top: 0;">{{POST_URL_DOMAIN}}</p>
                <p class="postBrief" style="color: gray; font: 11px 'lucida grande',tahoma,verdana,arial,sans-serif; margin-top: 5px;">{{POST_BRIEF}}</p>
            </div>
        </div>
        <p style="color: gray; font: 11px 'lucida grande',tahoma,verdana,arial,sans-serif; float: left; margin-top: 0;">
            <img src="https://s-static.ak.facebook.com/rsrc.php/v1/yT/r/4QVMqOjUhcd.gif" style="float: left; margin-right: 10px;" />
            <span style="display: inline-block; float: left; height: 16px; margin-top: 1px;"><a href="#" style="color: #6B84B4;">Beğen</a> · <a href="#" style="color: #6B84B4;">Yorum Yap</a> · birkaç saniye önce, <a href="#" style="color: gray;">Creasoup - Dev</a> ile</span>
        </p>
    </div>
</div>
<div class="clear"></div>