<div class="width_full noFloat clear center">
    <h2>Showing requests:</h2>
    <table>
        <thead>
            <tr>
                <th>Hour</th>
                <th>Doctor</th>
                <th>Patient</th>
                <th colspan="2">Details</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->requests as $request): ?>
            <tr>
                <td><?= $request->createdAt->format('Y-m-d H:i:s') ?></td>
                <td><?= $request->doctor->user->name ?></td>
                <td><?= $request->patient->name . ' ' . $request->patient->surname ?></td>
                <td><?= $request->details ?></td>
                <td><a class="lab" href="#respond<?= $request->id?>">Respond</a></td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>