<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>Hospital CRM</title>
        <link rel="stylesheet" href="<?= $this->baseUrl("/pub/cockpit/css/layout.css") ?>" type="text/css" media="screen" />
        <link rel="stylesheet" href="<?= $this->baseUrl("/pub/cockpit/css/smoothness/jquery-ui-1.8.16.custom.css") ?>" type="text/css" media="screen" />
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="<?= $this->baseUrl("/pub/cockpit/css/ie.css") ?>" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="<?= $this->baseUrl("/pub/cockpit/js/jquery-1.7.min.js") ?>"></script>
    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title" style="font-size: 125%;"><a href="<?= $this->baseUrl("/cockpit") ?>">Hospital CRM</a></h1>
                <h2 class="section_title">Dashboard</h2>
            </hgroup>
        </header> <!-- end of header bar -->
        
        <section id="secondary_bar">
            <div class="user">
                <p>Hello <?= $this->currentUser->name ?></p>
                <a class="logout_user" href="<?= $this->baseUrl("/cockpit/auth/logout") ?>" title="Logout">Logout</a>
            </div>
            <div class="breadcrumbs_container">
                <?= $this->breadCrumbs ?>
            </div>
        </section><!-- end of secondary bar -->
        
        <aside id="sidebar" class="column" style="height: 100%;">
            <form class="quick_search">
                <input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;" />
            </form>
            <hr/>
            <? if ('Administrator' == $this->role || 'Operator' == $this->role): ?>
            <h3>Patient Management</h3>
            <ul class="toggle">
                <li class="icn_add_user"><a href="<?= $this->baseUrl("/cockpit/patient/register") ?>">Registration</a></li>
                <li class="icn_view_users"><a href="<?= $this->baseUrl("/cockpit/patient/list") ?>">View all</a></li>
                <li class="icn_profile"><a href="<?= $this->baseUrl("/cockpit/patient/list?type=INPATIENT") ?>">Inpatient Management</a></li>
                <li class="icn_profile"><a href="<?= $this->baseUrl("/cockpit/patient/list?type=OUTPATIENT") ?>">Outpatient Management</a></li>
            </ul>
            <? endif; ?>
            <? if ('Administrator' == $this->role || 'Operator' == $this->role || 'Doctor' == $this->role): ?>
            <h3>Doctor Management</h3>
            <ul class="toggle">
                <? if ('Administrator' == $this->role || 'Operator' == $this->role): ?>
                <li class="icn_add_user"><a href="<?= $this->baseUrl("/cockpit/doctor/register") ?>">New Doctor</a></li>
                <li class="icn_view_users"><a href="<?= $this->baseUrl("/cockpit/doctor/list") ?>">View all</a></li>
                <? endif; ?>
                <li class="icn_categories"><a href="<?= $this->baseUrl("/cockpit/doctor/schedule") ?>">Schedules</a></li>
            </ul>
            <? endif; ?>
            <? if ('Administrator' == $this->role || 'Operator' == $this->role || 'Laboratory' == $this->role): ?>
            <h3>Laboratory Management</h3>
            <ul class="toggle">
                <li class="icn_folder"><a href="<?= $this->baseUrl("/cockpit/laboratory/request") ?>">View all requests</a></li>
            </ul>
            <? endif; ?>
            <? if ('Administrator' == $this->role || 'Operator' == $this->role): ?>
            <h3>Reports</h3>
            <ul class="toggle">
                <li class="icn_categories"><a href="<?= $this->baseUrl("/cockpit/report/patient") ?>">Patient</a></li>
            </ul>
            <? endif; ?>
        </aside><!-- end of sidebar -->
        
        <section id="main" class="column" style="height: 100%;">
            <?= $this->layout()->content ?>
            <div class="spacer"></div>
        </section>
        
        <script>
        function getUrl(path) {
            return "<?= $this->baseUrl("/cockpit") ?>" + path;
        }
        </script>
        <script src="<?= $this->baseUrl("/pub/cockpit/js/hideshow.js") ?>"></script>
        <script src="<?= $this->baseUrl("/pub/cockpit/js/jquery.tablesorter.min.js") ?>"></script>
        
        <script src="<?= $this->baseUrl("/pub/cockpit/js/jquery-ui-1.8.16.custom.min.js") ?>"></script>
        <script src="<?= $this->baseUrl("/pub/cockpit/js/jquery-ui-timepicker-addon.js") ?>"></script>

        <!-- Common JavaScript file -->
        <script src="<?= $this->baseUrl("/pub/cockpit/js/common.js?v2") ?>"></script>
    </body>
</html>