<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>Hospital CRM</title>
        <link rel="stylesheet" href="<?= $this->baseUrl("/pub/cockpit/css/layout.css") ?>" type="text/css" media="screen" />
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="<?= $this->baseUrl("/pub/cockpit/css/ie.css") ?>" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title" style="font-size: 125%;"><a href="<?= $this->baseUrl("/cockpit") ?>">Hospital CRM</a></h1>
                <h2 class="section_title">Giriş</h2>
            </hgroup>
        </header> <!-- end of header bar -->
        <section id="secondary_bar">
            <div class="user">
                <p>Merhaba ziyaretçi!</p>
            </div>
            <div class="breadcrumbs_container" style="height: 33px;">
                <article class="breadcrumbs">
                    <a href="<?= $this->baseUrl("/cockpit") ?>">Facebook Haber Paneli</a>
                    <div class="breadcrumb_divider"></div>
                    <a class="current">Giriş</a></article>
            </div>
        </section><!-- end of secondary bar -->
        <section id="login" class="width_full">
            <?= $this->layout()->content ?>
            <div class="spacer"></div>
        </section>
        <script src="<?= $this->baseUrl("/pub/cockpit/js/jquery-1.7.min.js") ?>"></script>
        <script src="<?= $this->baseUrl("/pub/cockpit/js/hideshow.js") ?>"></script>
    </body>
</html>