<? if (isset($this->meetings)): ?>
<div class="width_full noFloat clear center">
    <h2>Meetings:</h2>
    <table>
        <thead>
            <tr>
                <th>Area</th>
                <th>Doctor</th>
                <th>Hour</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->meetings as $meeting): ?>
            <tr>
                <td><?= $meeting->doctor->area ?></td>
                <td><?= $meeting->doctor->user->name ?></td>
                <? $now = new DateTime('now'); ?>
                <? if ($meeting->reservationDateTime < $now): ?>
                <td style="text-decoration: line-through;"><?= $meeting->reservationDateTime->format('Y-m-d H:i:s') ?></td>
                <? else: ?>
                <td><?= $meeting->reservationDateTime->format('Y-m-d H:i:s') ?></td>
                <? endif; ?>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>
<? endif; ?>
<div class="width_full noFloat clear center" id="patientEditFormWrapper">
    <h2>Details:</h2>
    <?= $this->partial('/error/error-item.phtml', $this->errorMessages['patient']) ?>
    <?= $this->form ?>
</div>